defaults:
  - default

_target_: dataset.conme.ConMeDataset

dataset_name: conme
task_name: conme_replace_obj

# Local dataset paths
data_root: /scratch/gpfs/nb0564/tda-multimodal/datasets/ConMe
csv_path: ${dataset.data_root}/replace-obj.csv
images_dir: ${dataset.data_root}/images

# Tokenizer reference (if a dataset class uses it)
tokenizer: ${model.tokenizer}

# Overrides for this dataset
batch_size: 8
seq_len: 256
n_seqs: 500
max_tokens: 512
shuffle: False

# Text-only prompt template (models are text LMs in this repo)
prompt_template: "Question: {question}\nOptions: {options}\nAnswer:"
use_images: true 